name = "EOM"
uuid = "cecae2fc-e4f4-4e50-9264-136db4e415fd"
authors = ["kakinumayuta <kakinuma.y.068@ms.saitama-u.ac.jp>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
